POST http://localhost:8080/api/logs
Content-Type: application/json

{
  "serviceName": "auth-service",
  "level": "ERROR",
  "message": "login failed",
  "responseTimeMs": 1200,
  "statusCode": 500
}

###

POST http://localhost:8080/api/logs

###

GET http://localhost:8080/api/logs

###

GET http://localhost:8080/api/logs/slow?ms=1000

### 에러 로그 조회
GET http://localhost:8080/api/logs/error

### 서비스별 로그 조회
GET http://localhost:8080/api/logs/service/auth-service

### 로그 통계 조회
GET http://localhost:8080/api/logs/stats


### 테스트 로그 추가(error)
POST http://localhost:8080/api/logs

Content-Type: application/json

{
  "level": "ERROR",
  "message": "login failed",
  "responseTimeMs": 1200,
  "serviceName": "auth-service",
  "statusCode": 500
}

### 테스트 로그 추가(INFO)
POST http://localhost:8080/api/logs

Content-Type: application/json

{
  "level": "INFO",
  "message": "user profile loaded",
  "responseTimeMs": 200,
  "serviceName": "user-service",
  "statusCode": 200
}

### 테스트 로그 추가(WARN)
POST http://localhost:8080/api/logs

Content-Type: application/json

{
  "level": "WARN",
  "message": "payment delayed",
  "responseTimeMs": 950,
  "serviceName": "payment-service",
  "statusCode": 200
}

### 테스트 로그 추가(ERROR 401)
POST http://localhost:8080/api/logs

Content-Type: application/json

{
  "level": "ERROR",
  "message": "token expired",
  "responseTimeMs": 400,
  "serviceName": "auth-service",
  "statusCode": 401
}

### 테스트 로그 추가(INFO 401)
POST http://localhost:8080/api/logs

Content-Type: application/json

{
  "level": "INFO",
  "message": "order completed",
  "responseTimeMs": 300,
  "serviceName": "order-service",
  "statusCode": 201
}

### Kafka 테스트(성공)
POST http://localhost:8080/api/logs
Content-Type: application/json

{
  "serviceName": "test-service",
  "level": "INFO",
  "message": "Kafka 테스트 메시지",
  "responseTimeMs": 100,
  "statusCode": 200
}

### Kafka 테스트 확인
GET http://localhost:8080/api/logs

### Kafka 테스트(실패)
POST http://localhost:8080/api/logs
Content-Type: application/json

{
  "invalidField": "이상한데이터"
}